apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-aws-ec2
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-ec2:v2