apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: ec2-s3-composition
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: XEC2S3Resource
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      # S3 Bucket
      - name: s3-bucket
        base:
          apiVersion: s3.aws.upbound.io/v1beta1
          kind: Bucket
          spec:
            forProvider:
              region: "us-east-1"
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.bucketName
          toFieldPath: metadata.name

      # Security Group
      - name: web-security-group
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: SecurityGroup
          spec:
            forProvider:
              description: "Security group for web application"
              ingress:
              - fromPort: 80
                toPort: 80
                protocol: "tcp"
                cidrBlocks: ["0.0.0.0/0"]
              - fromPort: 22
                toPort: 22
                protocol: "tcp"
                cidrBlocks: ["0.0.0.0/0"]
              egress:
              - fromPort: 0
                toPort: 0
                protocol: "-1"
                cidrBlocks: ["0.0.0.0/0"]
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              fmt: "%s-web-sg"

      # EC2 Instance with fixed UserData
      - name: ec2-instance
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: Instance
          spec:
            forProvider:
              instanceType: "t3.micro"
              ami: "ami-0c02fb55956c7d316"
              region: "us-east-1"
              associatePublicIpAddress: true
              vpcSecurityGroupIdSelector:
                matchControllerRef: true
              userData: |
                #!/bin/bash
                # Log everything for debugging
                exec > >(tee /var/log/user-data.log) 2>&1
                echo "UserData script started at $(date)"
                
                # Check which OS we're running
                if command -v dnf &> /dev/null; then
                    echo "Detected Amazon Linux 2023 - using dnf"
                    dnf update -y
                    dnf install -y httpd
                else
                    echo "Detected Amazon Linux 2 - using yum"
                    yum update -y
                    yum install -y httpd
                fi
                
                # Start and enable httpd
                systemctl start httpd
                systemctl enable httpd
                
                # Create webpage
                cat > /var/www/html/index.html << 'EOF'
                <!DOCTYPE html>
                <html>
                <head>
                    <title>Crossplane Demo</title>
                    <style>
                        body { 
                            font-family: Arial, sans-serif; 
                            margin: 0; 
                            padding: 40px;
                            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
                            color: white;
                            min-height: 100vh;
                        }
                        .container { 
                            background: rgba(255,255,255,0.1); 
                            padding: 40px; 
                            border-radius: 15px; 
                            text-align: center;
                            backdrop-filter: blur(10px);
                        }
                        h1 { font-size: 2.5em; margin-bottom: 20px; }
                        p { font-size: 1.2em; margin: 10px 0; }
                        .success { color: #50ff50; font-weight: bold; }
                    </style>
                </head>
                <body>
                    <div class="container">
                        <h1>🎉 Hello from Crossplane!</h1>
                        <p>This EC2 instance was deployed via <strong>ArgoCD + Crossplane</strong></p>
                        <p class="success">✅ Infrastructure as Code SUCCESS!</p>
                        <p>✅ Managed by: Crossplane</p>
                        <p>✅ Deployed via: ArgoCD GitOps</p>
                        <p>✅ Auto-configured with UserData!</p>
                        <p><em>Your GitOps pipeline is working perfectly! 🚀</em></p>
                    </div>
                </body>
                </html>
                EOF
                
                # Create health check
                echo "OK" > /var/www/html/health
                
                echo "UserData script completed at $(date)"
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.instanceType
          toFieldPath: spec.forProvider.instanceType
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.amiId
          toFieldPath: spec.forProvider.ami