apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xec2s3resources.platform.example.com
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-5"
spec:
  group: platform.example.com
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  region:
                    type: string
                    description: AWS region
                    default: "us-east-1"
                  instanceType:
                    type: string
                    description: EC2 instance type
                    default: "t3.micro"
                  bucketName:
                    type: string
                    description: S3 bucket name
                  amiId:
                    type: string
                    description: AMI ID for EC2 instance
                    default: "ami-0abcdef1234567890"
                  keyName:
                    type: string
                    description: EC2 key pair name (optional)
                required:
                - bucketName
            required:
            - parameters
  names:
    kind: XEC2S3Resource
    plural: xec2s3resources
  claimNames:
    kind: EC2S3Resource
    plural: ec2s3resources
