apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: ec2-s3-composition
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: ServerSideApply=true
    description: "This creates EC2 and S3"
    version: "v1.0.0"
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: XEc2S3

  resources:
  # EC2 Instance
  - name: ec2-web
    base:
      apiVersion: ec2.aws.upbound.io/v1beta2
      kind: Instance
      spec:
        forProvider:
          instanceType: t3.micro
          region: us-east-1
          ami: ami-0427090fd1714168b  # Amazon Linux 2023 us-east-1
          tags:
            Name: "HelloWorld"
            Component: "web-server"

  # S3 Bucket  
  - name: s3-bucket
    base:
      apiVersion: s3.aws.upbound.io/v1beta2
      kind: Bucket
      spec:
        forProvider:
          region: us-east-1
          tags:
            Environment: "Dev"
            Name: "MyBucket"
