apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: ec2-s3-composition
spec:
  mode: Resources  # Use legacy mode
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: XEc2S3
  resources:
  - name: ec2-instance
    base:
      apiVersion: ec2.aws.upbound.io/v1beta2
      kind: Instance
      spec:
        forProvider:
          instanceType: t3.micro
          region: us-east-1
          ami: ami-0427090fd1714168b
          tags:
            Name: "crossplane-ec2"
  - name: s3-bucket
    base:
      apiVersion: s3.aws.upbound.io/v1beta2  
      kind: Bucket
      spec:
        forProvider:
          region: us-east-1
          tags:
            Name: "crossplane-bucket"
