apiVersion: platform.example.com/v1alpha1
kind: Ec2S3
metadata:
  name: crossplane-composite
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Last
spec:
  projectName: "myapp"
  environment: "dev"
  ec2InstanceType: "t3.micro"
  ec2Region: "us-east-1"
  s3Region: "us-east-1"  # Same region for lower latency
