apiVersion: aws.m.upbound.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"  # Crear antes que otros recursos
spec:
  credentials:
    secretRef:
      namespace: crossplane-system
      name: aws-secret
      key: creds
    source: Secret
