apiVersion: s3.aws.m.upbound.io/v1beta1
kind: Bucket
metadata:
  name: webapp-s3
  labels:
    testing.upbound.io/example-name: s3
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Segundo
spec:
  forProvider:
    bucket: demo-webapp-s3-aldair  # ⚠️ CAMBIAR por nombre único
    region: us-east-2
    tags:
      foo: bar
      environment: demo
---
apiVersion: s3.aws.m.upbound.io/v1beta1
kind: BucketOwnershipControls
metadata:
  name: webapp-s3-ownership
  labels:
    testing.upbound.io/example-name: s3
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # Último
spec:
  forProvider:
    bucketRef:
      name: webapp-s3  # Referencia al objeto K8s, no al bucket AWS
    region: us-east-2
    rule:
    - objectOwnership: BucketOwnerPreferred
