apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: demo1
type: Opaque
data:
  creds: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQTJaQlY0VU1OVVpVR0JXSDQKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gYnQxcWFuY01UWGgxQ2xGS240TDVBZEpjNFZFejh0eWFtMlgwYlJhMwo=
